name: 05 - 01 - Event Filters and Activity Types
on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Running wheneber a pr is opened or synced to main"
        