name: 06 - Contexts

on:
  push:
  workflow_dispatch:
      inputs:
        deubg:
          type: boolean
          default: false
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs: 
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA ${{ github.sha }}"
          echo "Actor ${{ github.actor }}"
      - name: Retrieve Variable
        run: echo "MY_VAR is ${{ vars.MY_VAR }}"
      - name: Print Env variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env ${{ env.vars.MY_WORKFLOW_VAR }}"
          echo "Overwritten env ${{ env.vars.MY_OVERWRITTEN_VAR }}"  
      - name: Print Env variables 2
        run: |
          echo "Workflow env ${{ env.vars.MY_WORKFLOW_VAR }}"
          echo "Overwritten env ${{ env.vars.MY_OVERWRITTEN_VAR }}"  

