name: 11 - working with inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        default: false
      target:
        type: environment
        required: true
        description: "Which env the workflow will target"
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: release from which to build/deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building from tag ${{inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.dry-run == false }}
    environment: ${{ inputs.target }}
    steps:
      - name: deploy
        run: echo "deploying to ${{ inputs.target }}"