name: 12 - Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo ${{ vars.GITHUB_OUTPUT }}
      - name: Build
        id: build
        run: echo "status=${{ inputs.build-status }}"
        